// ============================================
// UNIFIED DATABASE SCHEMA EXPORTS
// Thai Binh University Training Platform
// ============================================
//
// This file exports all schemas from the pg/ directory
// Legacy schemas have been deprecated and moved to deprecated/
//
// Schema Organization:
// - auth: Users, sessions, accounts, organizations
// - academic: Courses, modules, lessons, departments
// - student: Students, enrollments, progress, assignments
// - certification: Certificates, blanks, registry books
// - finance: Invoices, payments, fee schedules

// Re-export all pg schemas with explicit exports
export {
  // Auth Schema
  users,
  sessions,
  accounts,
  organizations,
  members,
  invitations,
  verifications,
  profiles,
  jwks,
  organizationRoles,
  usersRelations,
  organizationsRelations,
  membersRelations,
  invitationsRelations,
  sessionsRelations,
  accountsRelations,
  profilesRelations,
  jwksRelations,
  organizationRolesRelations,
  memberRoleEnum,
  invitationStatusEnum,
  genderEnum,
  type User,
  type NewUser,
  type Organization,
  type NewOrganization,
  type Member,
  type NewMember,
  type Invitation,
  type NewInvitation,
  type Session,
  type NewSession,
  type Account,
  type NewAccount,
  type Verification,
  type NewVerification,
  type Profile,
  type NewProfile,
  type Jwks,
  type NewJwks,
  type OrganizationRole,
  type NewOrganizationRole,
  type MemberRole,
  type InvitationStatus,
  type Gender,
  authSchema,
  
  // Academic Schema
  categories,
  departments,
  courses,
  modules,
  lessons,
  teachers,
  courseAssignments,
  waitlist,
  categoriesRelations,
  departmentsRelations,
  coursesRelations,
  modulesRelations,
  lessonsRelations,
  teachersRelations,
  courseAssignmentsRelations,
  waitlistRelations,
  departmentTypeEnum,
  courseStatusEnum,
  admissionModeEnum,
  lessonTypeEnum,
  teacherRoleEnum,
  waitlistStatusEnum,
  type Category,
  type NewCategory,
  type Department,
  type NewDepartment,
  type Course,
  type NewCourse,
  type Module,
  type NewModule,
  type Lesson,
  type NewLesson,
  type Teacher,
  type NewTeacher,
  type CourseAssignment,
  type NewCourseAssignment,
  type Waitlist,
  type NewWaitlist,
  type DepartmentType,
  type CourseStatus,
  type AdmissionMode,
  type LessonType,
  type TeacherRole,
  type WaitlistStatus,
  academicSchema,
  
  // Student Schema
  students,
  enrollments,
  progress,
  assignments,
  submissions,
  applications,
  studentsRelations,
  enrollmentsRelations,
  progressRelations,
  assignmentsRelations,
  submissionsRelations,
  type Student,
  type NewStudent,
  type Enrollment,
  type NewEnrollment,
  type Progress,
  type NewProgress,
  type Assignment,
  type NewAssignment,
  type Submission,
  type NewSubmission,
  type Application,
  type NewApplication,
  type StudentStatus,
  type EnrollmentStatus,
  type AssignmentType,
  type SubmissionStatus,
  type ApplicationStatus,
  studentSchema,
  
  // Certification Schema
  certificateBlankBatches,
  certificateBlanks,
  registryBooks,
  registryBookEntries,
  certificates,
  certificateWorkflowSteps,
  preCheckRecords,
  certificateBlankBatchesRelations,
  certificateBlanksRelations,
  registryBooksRelations,
  registryBookEntriesRelations,
  certificatesRelations,
  certificateWorkflowStepsRelations,
  type CertificateBlankBatch,
  type CertificateBlank,
  type RegistryBook,
  type RegistryBookEntry,
  type Certificate,
  type CertificateWorkflowStep,
  type PreCheckRecord,
  certificationSchema,
  
  // Finance Schema
  feeSchedules,
  invoices,
  invoiceItems,
  payments,
  refunds,
  scholarships,
  scholarshipApplications,
  feeSchedulesRelations,
  invoicesRelations,
  invoiceItemsRelations,
  paymentsRelations,
  refundsRelations,
  scholarshipsRelations,
  scholarshipApplicationsRelations,
  feeTypeEnum,
  invoiceStatusEnum,
  paymentMethodEnum,
  paymentStatusEnum,
  refundStatusEnum,
  scholarshipApplicationStatusEnum,
  type FeeSchedule,
  type NewFeeSchedule,
  type Invoice,
  type NewInvoice,
  type InvoiceItem,
  type NewInvoiceItem,
  type Payment,
  type NewPayment,
  type Refund,
  type NewRefund,
  type Scholarship,
  type NewScholarship,
  type ScholarshipApplication,
  type NewScholarshipApplication,
  type FeeType,
  type InvoiceStatus,
  type PaymentMethod,
  type PaymentStatus,
  type RefundStatus,
  type ScholarshipApplicationStatus,
  financeSchema,
} from './pg';
